server:
  port: 10000
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-payment?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.augustus.payment.mapper: debug
eureka:
  client:
    register-with-eureka: true #将服务注册到eureka
    fetch-registry: true #从eureka中获取服务列表默认为true, 单机可不写集群必须写
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka #eureka的地址
  instance:
    instance-id: payment-service-10000 #指定实例id
    prefer-ip-address: true # 显示真实的ip地址