server:
  port: 88
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route_payment
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
            - After=2020-06-04T14:03:15.314+08:00[Asia/Shanghai]
            - Cookie=username, lyj
            - Header=X-real-IP, \d+
            - Query=username, lyj
          filters:
            - AddResponseHeader=gateway-filter-header, yes
            - RewritePath=/payment-service(?<segment>/?.*), $\{segment}
eureka:
  client:
    register-with-eureka: true #将服务注册到eureka
    fetch-registry: true #从eureka中获取服务列表默认为true, 单机可不写集群必须写
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka #eureka的地址
  instance:
    instance-id: gateway #指定实例id
    prefer-ip-address: true # 显示真实的ip地址