server:
  port: 11066
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.110:8848
        service: ${spring.application.name}
    sentinel:
      transport:
        dashboard: localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'