server:
  port: 7001
spring:
  application:
    name: eureka-service-7001
eureka:
  instance:
    hostname: eureka7001 #eureka注册中心IP地址
  client:
    register-with-eureka: false #不将自己注册到注册中心
    fetch-registry: false #表示eureka不会从注册中心获取注册的服务的列表
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/ #集群配置则写其他节点的eureka地址