server:
  port: 22000
spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.110:8848
        service: ${spring.application.name}
    alibaba:
      seata:
        tx-service-group: shop_tx_group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.110:3306/seata_account
    username: root
    password: 123456
logging:
  level:
    io.seata: info
    org.augustus.account.mapper: debug
mybatis:
  mapper-locations: classpath:mapper/**/*.xml